spring:
  main:
    web-application-type: NONE
    web-environment: false

run:
  parameters:
    osm-discussion-page:
    osm-wiki-documentation-page:
    openstreetmap-api-url: "https://api.openstreetmap.org/api/0.6/"
    token: "dummy"
    token-secret: "dummy"
    consumer-key: "dummy"
    consumer-secret: "dummy"
    path-to-violations-file:
    max-violations-per-changeset: 50
    verifier:
      ways-have-matching-nodes:
        active: true
      duplicating-way-has-tags:
        active: true
      duplicating-way-is-not-member-of-any-relation:
        active: true
      inner-ring-way-has-no-tags:
        active: true
      inner-ring-way-is-only-member-of-violating-relation:
        active: true
      source:
        active: true
        tag-values: [ "NRCan-CanVec-10.0","NRCan-CanVec-8.0","NRCan-CanVec-7.0","CanVec 6.0 - NRCan" ]
